// import React from "react"

export const airLineData = [
  {
    id: 2,
    id_airline: 2,
    id_destination: 1,
    day: "monday",
    date: "20",
    month: "August",
    years: "2020",
    time_leave: "08:00",
    time_arrive: "12:00",
    transit: "0",
    price: 200000,
    code: "CS-123",
    terminal: "A",
    gate: "123",
    id_class: 1,
    deletedBy: 0,
    airline: {
      id: 2,
      name: "Lion Air",
      picture: "/uploads/1629652460002.png",
      extra_price: 30000,
    },
    destination: {
      id: 1,
      picture: null,
      destination_country: "Korea",
      destination_country_code: "KOR",
      destination_city: "Seoul",
      base_country: "Indonesia",
      base_country_code: "IDN",
      base_city: "Jakarta",
    },
    class: {
      id: 1,
      name: "Economy",
      add_price: 20000,
    },
    product_facility: {
      id: 2,
      facility: {
        id: 1,
        name: "Wifi",
      },
    },
  },
  {
    id: 3,
    id_airline: 3,
    id_destination: 1,
    day: "Tuesday",
    date: "20",
    month: "August",
    years: "2020",
    time_leave: "08:00",
    time_arrive: "12:00",
    transit: "3",
    price: 150000,
    code: "CS-123",
    terminal: "A",
    gate: "123",
    id_class: 1,
    deletedBy: 0,
    airline: {
      id: 3,
      name: "Adam Air",
      picture: "/upload/1629789819603.png",
      extra_price: 20000,
    },
    destination: {
      id: 1,
      picture: null,
      destination_country: "Korea",
      destination_country_code: "KOR",
      destination_city: "Seoul",
      base_country: "Indonesia",
      base_country_code: "IDN",
      base_city: "Jakarta",
    },
    class: {
      id: 1,
      name: "Economy",
      add_price: 20000,
    },
    product_facility: {
      id: 3,
      facility: {
        id: 1,
        name: "Wifi",
      },
    },
  },
  {
    id: 1,
    id_airline: 1,
    id_destination: 2,
    day: "monday",
    date: "20",
    month: "August",
    years: "2020",
    time_leave: "08:00",
    time_arrive: "12:00",
    transit: "1",
    price: 250000,
    code: "CS-123",
    terminal: "A",
    gate: "123",
    id_class: 1,
    deletedBy: 0,
    airline: {
      id: 1,
      name: "Air Asia",
      picture: "/uploads/1629652400190.svg",
      extra_price: 50000,
    },
    destination: {
      id: 2,
      picture: "/uploads/1629704264246.jpg",
      destination_country: "Japan",
      destination_country_code: "JPN",
      destination_city: "Tokyo",
      base_country: "Indonesia",
      base_country_code: "IDN",
      base_city: "Jakarta",
    },
    class: {
      id: 1,
      name: "Economy",
      add_price: 20000,
    },
    product_facility: {
      id: 1,
      facility: {
        id: 2,
        name: "Luggage",
      },
    },
  },
  {
    id: 4,
    id_airline: 4,
    id_destination: 2,
    day: "Tuesday",
    date: "20",
    month: "August",
    years: "2020",
    time_leave: "09:00",
    time_arrive: "13:00",
    transit: "1",
    price: 250000,
    code: "CS-123",
    terminal: "A",
    gate: "123",
    id_class: 1,
    deletedBy: 0,
    airline: {
      id: 4,
      name: "Garuda Indonesia",
      picture: "/uploads/1629652522020.png",
      extra_price: 30000,
    },
    destination: {
      id: 2,
      picture: "/uploads/1629704264246.jpg",
      destination_country: "Japan",
      destination_country_code: "JPN",
      destination_city: "Tokyo",
      base_country: "Indonesia",
      base_country_code: "IDN",
      base_city: "Jakarta",
    },
    class: {
      id: 1,
      name: "Economy",
      add_price: 20000,
    },
    product_facility: {
      id: 4,
      facility: {
        id: 1,
        name: "Wifi",
      },
    },
  },
  {
    id: 5,
    id_airline: 4,
    id_destination: 2,
    day: "Tuesday",
    date: "20",
    month: "August",
    years: "2020",
    time_leave: "10:00",
    time_arrive: "14:00",
    transit: "1",
    price: 250000,
    code: "CS-123",
    terminal: "A",
    gate: "123",
    id_class: 1,
    deletedBy: 0,
    airline: {
      id: 4,
      name: "Garuda Indonesia",
      picture: "/uploads/1629652522020.png",
      extra_price: 30000,
    },
    destination: {
      id: 2,
      picture: "/uploads/1629704264246.jpg",
      destination_country: "Japan",
      destination_country_code: "JPN",
      destination_city: "Tokyo",
      base_country: "Indonesia",
      base_country_code: "IDN",
      base_city: "Jakarta",
    },
    class: {
      id: 1,
      name: "Economy",
      add_price: 20000,
    },
    product_facility: {
      id: 5,
      facility: {
        id: 3,
        name: "In-Flight Meal",
      },
    },
  },
];
